CREATE TABLE IF NOT EXISTS listings (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_id     VARCHAR(255),
    source          VARCHAR(20)   NOT NULL,
    title           VARCHAR(512)  NOT NULL,
    description     VARCHAR(4000),
    price           DECIMAL(10, 2),
    rooms           REAL,
    area_sqm        REAL,
    address         VARCHAR(512)  NOT NULL,
    latitude        DOUBLE,
    longitude       DOUBLE,
    url             VARCHAR(1024) NOT NULL UNIQUE,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    net_rent        DECIMAL(10, 2),
    operating_costs DECIMAL(10, 2),
    vat             DECIMAL(10, 2),
    deposit         DECIMAL(10, 2),
    available_from  VARCHAR(255),
    provision       VARCHAR(255),
    build_year      INTEGER,
    heating_demand  REAL,
    fgee            REAL,
    benefits        VARCHAR(4000),
    image_urls      VARCHAR(4000),
    thumbnail_url   VARCHAR(1024),
    has_360_view    BOOLEAN NOT NULL DEFAULT FALSE,
    matterport_url  VARCHAR(1024)
);
